# Generated by Django 4.2 on 2023-04-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "api_secret_key",
                    models.CharField(max_length=200, verbose_name="API Secret key"),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False, verbose_name="Is a valid group?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Title of campaign"),
                ),
                (
                    "resource_name",
                    models.CharField(
                        choices=[
                            ("forms", "Forms"),
                            ("fundraising_pages", "Donations"),
                            ("petitions", "Petitions"),
                        ],
                        max_length=50,
                        verbose_name="API Resource name",
                    ),
                ),
                (
                    "api_response_json",
                    models.JSONField(verbose_name="API Response JSON"),
                ),
                (
                    "action_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.actiongroup",
                    ),
                ),
            ],
        ),
    ]
