# Generated by Django 4.2 on 2023-04-26 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="nome do grupo"),
                ),
                (
                    "an_secret_key",
                    models.CharField(
                        help_text="chave secreta do seu grupo na API da Action Network",
                        max_length=200,
                        verbose_name="chave secreta da API",
                    ),
                ),
                (
                    "openapi_token",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Usado para fazer autenticação dos recursos na OpenAPI",
                        max_length=85,
                        unique=True,
                        verbose_name="token de autenticação",
                    ),
                ),
            ],
            options={
                "verbose_name": "comunidade",
                "verbose_name_plural": "comunidades",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given_name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "family_name",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="sobrenome"
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "email_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="endereço de email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="telefone"
                    ),
                ),
                (
                    "action_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.actiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "alvo",
                "verbose_name_plural": "alvos",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=110, verbose_name="slug")),
                ("label", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "action_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.actiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.CreateModel(
            name="PostalAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_lines",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="endereço"
                    ),
                ),
                (
                    "locality",
                    models.CharField(blank=True, max_length=80, verbose_name="cidade"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="estado"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=30, verbose_name="cep"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=30, verbose_name="país"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postal_addresses",
                        to="actionnetwork.person",
                        verbose_name="pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="número de telefone"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="actionnetwork.person",
                        verbose_name="pessoa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="tags",
            field=models.ManyToManyField(blank=True, to="actionnetwork.tag"),
        ),
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="endereço de email"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="actionnetwork.person",
                        verbose_name="pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nome do campo")),
                (
                    "value",
                    models.CharField(max_length=150, verbose_name="valor do campo"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="actionnetwork.person",
                        verbose_name="pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="nome da campanha"),
                ),
                (
                    "resource_name",
                    models.CharField(
                        choices=[
                            ("forms", "Formulário"),
                            ("fundraising_pages", "Doação"),
                            ("petitions", "Petição"),
                            ("advocacy_campaigns", "Pressão"),
                        ],
                        max_length=50,
                        verbose_name="tipo de campanha",
                    ),
                ),
                (
                    "an_response_json",
                    models.JSONField(verbose_name="resposta da action network"),
                ),
                (
                    "action_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.actiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "campanha",
                "verbose_name_plural": "campanhas",
            },
        ),
    ]
