# Generated by Django 4.2 on 2023-04-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0002_person_submission_signature_postaladdress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="api_response_json",
            field=models.JSONField(default="", verbose_name="API Response JSON"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="api_response_json",
            field=models.JSONField(default={}, verbose_name="API Response JSON"),
            preserve_default=False,
        ),
    ]
