# Generated by Django 4.2 on 2023-04-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="nome do grupo")),
                (
                    "targets",
                    models.ManyToManyField(
                        to="actionnetwork.target", verbose_name="alvos"
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo de alvos",
                "verbose_name_plural": "grupos de alvos",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_groups",
            field=models.ManyToManyField(blank=True, to="actionnetwork.targetgroup"),
        ),
    ]
