# Generated by Django 4.2 on 2023-04-26 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("actionnetwork", "0003_targetgroup_campaign_target_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiongroup",
            name="users",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="mobilizadores"
            ),
        ),
    ]
