# Generated by Django 4.2 on 2023-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0003_signature_api_response_json_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="api_response_json",
            field=models.JSONField(blank=True, verbose_name="API Response JSON"),
        ),
    ]
