# Generated by Django 4.2 on 2023-04-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0004_alter_actiongroup_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("twilio", "Twilio")],
                        max_length=100,
                        verbose_name="nome da integração",
                    ),
                ),
                ("config", models.JSONField(verbose_name="configuração")),
                (
                    "action_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.actiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "integração",
                "verbose_name_plural": "integrações",
            },
        ),
    ]
