# Generated by Django 4.2 on 2023-04-14 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0005_donation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signature",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="signature",
            name="person",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="person",
        ),
        migrations.DeleteModel(
            name="Donation",
        ),
        migrations.DeleteModel(
            name="Signature",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
