# Generated by Django 4.2 on 2023-04-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0005_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="tags",
            field=models.ManyToManyField(blank=True, to="actionnetwork.tag"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("slug", "action_group")},
        ),
    ]
