# Generated by Django 4.2 on 2023-04-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0006_campaign_tags_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="name",
            field=models.CharField(
                choices=[("twilio", "Twilio"), ("sendgrid", "Sendgrid")],
                max_length=100,
                verbose_name="nome da integração",
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[("post_action", "Pós ação")],
                        default="post_action",
                        max_length=30,
                        verbose_name="tipo de email",
                    ),
                ),
                (
                    "from_name",
                    models.CharField(max_length=20, verbose_name="nome do remetente"),
                ),
                (
                    "from_email",
                    models.EmailField(
                        max_length=254, verbose_name="email do remetente"
                    ),
                ),
                ("subject", models.CharField(max_length=40, verbose_name="assunto")),
                ("content", models.TextField(verbose_name="conteúdo")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.campaign",
                    ),
                ),
            ],
        ),
    ]
