# Generated by Django 4.2 on 2023-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0007_alter_campaign_action_group_delete_actiongroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="family_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Family name"
            ),
        ),
    ]
