# Generated by Django 4.2 on 2023-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionnetwork", "0008_alter_person_family_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="api_response_json",
            field=models.JSONField(verbose_name="API Response JSON"),
        ),
    ]
