services:
  openapi:
    image: ${DOCKER_IMAGE:-nossas/openapi:main}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:80}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-project.settings.production}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-openapi.bonde.org,openapi.staging.bonde.org}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT:-True}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - TWILIO_WEBHOOK_URL=${TWILIO_WEBHOOK_URL:-https://openapi.staging.bonde.org}
    labels:
      - traefik.http.services.openapi.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.openapi.tls=true
      - traefik.http.routers.openapi.tls.certresolver=myresolver

networks:
  default:
    name: bonde