# Generated by Django 4.2 on 2023-04-24 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersgroup",
            name="token",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=85,
                unique=True,
                verbose_name="external token",
            ),
        ),
    ]
