# Generated by Django 4.2 on 2023-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0002_usersgroup_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersgroup",
            name="is_valid",
        ),
        migrations.AlterField(
            model_name="usersgroup",
            name="api_secret_key",
            field=models.CharField(
                max_length=200, verbose_name="Action Network API Secret key"
            ),
        ),
        migrations.AlterField(
            model_name="usersgroup",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Action Network Name"),
        ),
    ]
