# Generated by Django 4.2 on 2023-04-24 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0003_remove_usersgroup_is_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersgroup",
            name="api_secret_key",
            field=models.CharField(max_length=200, verbose_name="API Secret Key"),
        ),
        migrations.AlterField(
            model_name="usersgroup",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="usersgroup",
            name="token",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                help_text="Used to authentication OpenAPI",
                max_length=85,
                unique=True,
                verbose_name="Authentication Token",
            ),
        ),
    ]
