# Generated by Django 4.2 on 2023-04-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("actionnetwork", "0010_alter_campaign_resource_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="call sid"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("queued", "Queued"),
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                        verbose_name="call status",
                    ),
                ),
                ("from_number", models.CharField(max_length=25, verbose_name="from")),
                ("to_number", models.CharField(max_length=25, verbose_name="to")),
            ],
        ),
        migrations.CreateModel(
            name="TargetPhonePressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "phone_number",
                    models.CharField(max_length=25, verbose_name="phone number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhonePressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(verbose_name="Created date")),
                (
                    "api_response_json",
                    models.JSONField(verbose_name="API Response JSON"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.campaign",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.person",
                    ),
                ),
                ("targets", models.ManyToManyField(to="phone.targetphonepressure")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
