# Generated by Django 4.2 on 2023-04-27 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonepressure",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="data de criação"
            ),
        ),
    ]
